name: tracking
description: FocusFlow app
publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1

  # State + utils
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # Notifications + timezone
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^5.0.1

  # Widget
  home_widget: ^0.6.0

  # Battery help intent
  android_intent_plus: ^5.2.0

  # Export
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  csv: ^6.0.0
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
